---
version: '3.7'

services:
  magic:
    build:
      context: ./
      dockerfile: dockerfile
    image: magic
    command: yarn start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
